title: Andrey Denisov CV
description: Backend Developer | Java, Spring, Docker, Kafka
url: https://github.com/andrey-2077.io/cv
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml
