title: Andrey Denisov CV
description: Backend Developer | Java, Spring, Docker, Kafka
url: "https://andrey-2077.github.io"
baseurl: "/jekyll-cv"
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml
